### ISSUE TITLE
Python meta upgrade

### ISSUE THREAD

**Issue by sbancal** [EPFL-ENAC/ENACrestic#8]
- [x] Migrate from pipenv to poetry
- [x] https://github.com/googleapis/release-please
- [ ] #20 - is delayed so that we won't trigger many new releases in current phase (to prevent users to be notified many times)
